version: "3.8"

services:
  db:
    image: postgres:15
    container_name: roamie_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: RoamieTeamUp2026
      POSTGRES_DB: roamie
    ports:
      - "5432:5432"
    volumes:
      - roamie_db_data:/var/lib/postgresql/data
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql

volumes:
  roamie_db_data: