export const TAG_OPTIONS = [
"🧭 Professional wanderer",
  "🎒 Side quest enthusiast",
  "🌱 Touching grass competitively",
  "⭐ Locally legendary",
  "🦝 Neighborhood loot goblin",
  "🎬 Walking for the plot",
  "✨ Collecting little treasures",
  "🗺️ Casually off the map",
  "📴 Socially AFK",
  "🚶 Out here roaming",
  "🌀 Chronically exploring",
  "🧱 Built for side quests",
  "🌤️ Suspiciously outdoors",
  "🎁 Certified item hunter",
  "💎 Rare drop energy",
  "👑 Main character in my zip code",
  "📖 Walking into lore",
  "🛑 I brake for loot",
  "🔍 Fueled by curiosity",
  "➡️ Just one more block",
  "👹 Map goblin",
  "☀️ Outside by choice",
  "🌿 Grass touched recently",
  "⏱️ Neighborhood speedrun",
  "🎯 Side quest locked in",
  "🧠 Treasure brain",
  "📍 Going where the loot is",
  "🌲 Catch me in the wild",
  "😈 Mildly feral, very local",
  "📈 Exploration-maxxing",
  "✨ I saw shiny and followed it",
  "🪴 Low stakes adventurer",
  "🏙️ Hyperlocal icon",
  "😵 Roaming irresponsibly",
  "🚶‍➡️ Walked here for no reason",
  "👀 Too curious for my own good",
  "🎲 Accidentally on an adventure",
  "🏆 Local legend in training",
  "🎮 Open-world behavior",
  "📦 Collect first, ask later",
  "💊 Loot-pilled",
  "🧸 Tiny quest enjoyer",
  "🎮 Streetpass soul",
  "🏃 Roam now, question later",
  "🎭 Unnecessarily committed to the bit",
  "💖 Emotionally attached to collectibles",
  "🦝 Digital treasure raccoon",
  "🌤️ Outside arc",
  "🗣️ NPCs know me here",
  "⚡ Powered by side quests",
  "🏠 One more drop then I go home",
  "🕹️ Walking simulator champion",
  "💯 Peak roaming form",
  "🪨 Vibes: found object",
  "🌱 Touch grass elite",
  "👁️ Currently being perceived outdoors",
  "👹 Gremlin for rare items",
  "🎯 Looting with purpose",
  "🧃 Small adventure specialist",
  "😼 Neighborhood menace",
  "🛣️ I know a shortcut",
  "🌍 Open-world citizen",
  "🎒 Inventory over capacity",
  "🧐 Collectible connoisseur",
  "❤️ The map and I are in a relationship",
  "🧭 Somewhere between lost and thriving",
  "📡 Unclaimed loot detector",
  "🕵️ My route is classified",
  "💼 Exploring on company time",
  "🛝 Public park cryptid",
  "🌫️ Mysterious but nearby",
  "🏁 I came, I saw, I collected",
  "🏅 Zip code champion",
  "🍄 Foraging but digital",
  "😇 Chaotic good explorer",
  "🚶 Walking around like it means something",
  "🧍 Found another little guy",
  "🏛️ Local discovery department",
  "🔁 Cannot stop finding things",
  "🐹 Stepping outside for enrichment",
  "🍬 A little treat collector",
  "📱 This could have been a text",
  "🧌 Outdoor gremlin",
  "🎲 Real-world RNG enjoyer",
  "🥇 S-ranking the neighborhood",
  "📦 Collectibles before responsibilities",
  "🌳 Nature but gamified",
  "🤝 Community core",
  "🧭 Roaming with intent",
  "✅ Passive quest completion",
  "🫂 Local co-op energy",
  "🛍️ Just here for the exclusives",
  "📡 Human Streetpass notification",
  "💨 Sneaking in light cardio",
  "🗺️ Exploring the spawn area",
  "🔓 New area unlocked",
  "🏪 I support local side quests",
  "💰 The loot was worth it",
  "👥 Friendship encounter possible",
  "🧾 Running errands like an RPG",
  "🧠 Hyperfixated on nearby",
  "🌟 Outside in legendary mode",
  "🌍 Geographically curious",
  "🔄 Trade offer pending",
  "🎭 Emotionally sponsored by side quests",
  "🚶 Walking to discover, not to arrive",
  "🕵️ If it's nearby, I'm investigating",
  "🗺️ This neighborhood has secrets",
  "📍 Plotting my next roam",
  "🧩 Interactive environment enjoyer",
  "🎞️ Collecting memories and trinkets",
  "💬 Social encounter unlocked",
  "🦄 I do it for the rare spawn",
  "📋 Neighborhood completionist",
  "☕ Café discovered",
  "🌳 Park discovered",
  "🛤️ Secret route enthusiast",
  "❓ Vaguely on a mission",
  "🎠 I love locally sourced whimsy",
  "🌱 Outdoor enrichment arc",
  "👃 Too nosy to stay inside",
  "🧭 Not lost, just exploring",
  "🎓 Side quest scholarship recipient",
  "🤝 Community encounter build",
  "💊 Trade-pilled",
  "👜 Curiosity with pockets",
  "📍 I found this place by accident",
  "📚 One with the local lore",
  "💫 Limited edition behavior",
  "🎁 I came outside for loot",
  "🌀 Wandering with benefits",
  "🚪 Walking around unlocked something in me",
  "🎯 Local drop chaser",
  "🧠 I collect, therefore I am",
  "🫡 Extrovert by proximity",
  "🛣️ Street-level adventurer",
  "🏘️ Suburban fantasy protagonist",
  "🗺️ The block is my open world",
  "📢 Rare item propaganda victim",
  "🎒 My inventory tells a story",
  "🙂 Just roaming, respectfully",
  "✨ Bringing back whimsy",
  "📍 Geocached in spirit",
  "🧚 Urban fairy behavior",
  "⚡ Too powerful when outdoors",
  "💊 Roam pilled",
  "🧠 The neighborhood remembers me",
  "🏛️ I have business in this district",
  "🎒 A collector with range",
  "🌱 Touch grass tactician",
  "🚶 Walkable city enjoyer",
  "📈 Wander-maxxed",
  "📜 Gathering side lore",
  "📦 I heard there was a drop here",
  "🌿 The local ecosystem knows my name",
  "🗺️ Map screen addict",
  "😵‍💫 I just wanted fresh air and now this",
  "🪩 Tiny whimsy collector",
  "☁️ Rarely indoors mentally",
  "🛣️ Roads? opportunities",
  "💬 The social feature activated me",
  "👹 Community event final boss",
  "📣 Item-trading evangelist",
  "🏕️ Spawn camping the park",
  "🎯 Walking around with secret objectives",
  "🫥 Zero thoughts, all discovery",
  "🎪 I support local whimsy",
  "💫 Collecting little moments",
  "🌤️ This is my exploration era",
  "🎮 Playable character energy",
  "✅ The roam was successful",
  "🧲 Unreasonably good at finding stuff",
  "🧠 Loot instincts unmatched",
  "📍 I know where the good drops are",
  "🏛️ Civic engagement but fun",
  "🌎 Encountering the world",
  "🧌 Just a little neighborhood cryptid",
  "📱 Outside because the app told me to",
  "🎬 Neighborhood arc in progress",
  "🪪 Side quest citizen",
  "🌀 Whimsy-driven navigation",
  "🤝 Community-centered gremlin",
  "↪️ I fear no detour",
  "🚚 Trade route specialist",
  "🪑 Park bench proximity bonus",
  "🤲 Collectible diplomacy",
  "🌤️ Going outside for enrichment purposes"
];

export default TAG_OPTIONS;